version: "3"
services:
    homeassistant:
        container_name: home-assistant
        image: homeassistant/raspberrypi4-homeassistant:stable
        volumes:
            - ${HOME}/homeassistant_config/:/config
            - /etc/tellstick.conf:/etc/tellstick.conf
        devices:
            - /dev/bus/usb:/dev/bus/usb
        environment:
            - TZ=Europe/Stockholm
        restart: always
        network_mode: host
    syncthing:
        container_name: syncthing
        image: syncthing/syncthing:latest
        user: ${USERID}
        network_mode: host
        restart: always
        volumes:
            - ${HOME}/syncthing_volume:/var/syncthing
    foggy:
        container_name: foggy
        image: e9wikner/foggy:latest
        logging:
            driver: journald
            options:
                tag: "foggy"
        ports:
            - 21210:21210
        volumes:
            - /etc/avahi/services/:/etc/avahi/services/
            - ${HOME}/syncthing_volume/folders/stefans/pictures:/pictures
        user: ${USERID}
