version: "3"
services:
    homeassistant:
        container_name: home-assistant
        image: homeassistant/raspberrypi4-homeassistant:stable
        volumes:
            - /home/e9wikner/homeassistant_config/:/config
            - /home/e9wikner/tellstick.conf:/etc/tellstick.conf
        devices:
            - /dev/bus/usb:/dev/bus/usb
        environment:
            - TZ=Europe/Stockholm
        restart: always
        network_mode: host
    syncthing:
        image: syncthing/syncthing:latest
        user: ${SYNCTHING_USER}
        network_mode: host
        restart: always
        volumes:
            - /home/e9wikner/syncthing_volume:/var/syncthing
