version: "3"
services:
    home-assistant:
        container_name: home-assistant
        image: homeassistant/raspberrypi4-homeassistant:stable
        volumes:
            - ${HOME}/homeassistant_config/:/config
            - /etc/tellstick.conf:/etc/tellstick.conf
            - /tmp/TelldusClient:/tmp/TelldusClient
            - /tmp/TelldusEvents:/tmp/TelldusEvents
        devices:
            - /dev/bus/usb:/dev/bus/usb
        privileged: true
        environment:
            - TZ=Europe/Stockholm
        restart: always
        network_mode: host
    syncthing:
        container_name: syncthing
        image: syncthing/syncthing:latest
        user: ${USERID}
        network_mode: host
        restart: always
        volumes:
            - ${HOME}/syncthing_volume:/var/syncthing
    plex:
        container_name: plex
        image: ghcr.io/linuxserver/plex
        environment:
            - TZ=Europe/Stockholm
            - VERSION=docker
        network_mode: host
        restart : unless-stopped
        volumes:
            - ${HOME}/plex/config:/config \
            - ${HOME}/plex/var/transcode:/transcode \
            - ${HOME}/plex/movies:/movies
            - ${HOME}/plex/tv:/tv
