version: "3"
services:
    home-assistant:
        container_name: home-assistant
        image: ghcr.io/home-assistant/raspberrypi3-homeassistant:stable
        volumes:
            - ./config/:/config
            - /etc/tellstick.conf:/etc/tellstick.conf
            - /tmp/TelldusClient:/tmp/TelldusClient
            - /tmp/TelldusEvents:/tmp/TelldusEvents
        devices:
            - /dev/bus/usb:/dev/bus/usb
        privileged: true
        environment:
            - TZ=Europe/Stockholm
        restart: always
        network_mode: host