- id: '1634837623480'
  alias: Tänd på morgonen
  description: ''
  trigger:
  - platform: time
    at: 07:30
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - service: switch.turn_on
    target:
      entity_id:
      - switch.switch_1_i_koket
      - switch.switch_2_i_allrumet
      - switch.switch_4_i_vardagsrummet
      - switch.switch_5_i_vardagsrummet
      - switch.switch_6_i_hallen
      - switch.switch_7_vid_ytterdorren
      - switch.switch_8_vid_tvattstugan
      - switch.switch_9_till_baksidan
      - switch.switch_10_till_gastrummet
      - switch.switch_11_till_kontoret
      - switch.switch_12_vid_altanen
      - switch.switch_3_i_vardagsrummet
  mode: single
- id: '1634837623481'
  alias: Slack när solen går upp
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.switch_1_i_koket
      - switch.switch_2_i_allrumet
      - switch.switch_4_i_vardagsrummet
      - switch.switch_5_i_vardagsrummet
      - switch.switch_6_i_hallen
      - switch.switch_7_vid_ytterdorren
      - switch.switch_8_vid_tvattstugan
      - switch.switch_9_till_baksidan
      - switch.switch_10_till_gastrummet
      - switch.switch_11_till_kontoret
      - switch.switch_12_vid_altanen
      - switch.switch_3_i_vardagsrummet
  mode: single
- id: '1634837623482'
  alias: Tänd när solen går ner
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: time
    before: '22:59'
  action:
  - service: switch.turn_on
    target:
      entity_id:
      - switch.switch_1_i_koket
      - switch.switch_2_i_allrumet
      - switch.switch_4_i_vardagsrummet
      - switch.switch_5_i_vardagsrummet
      - switch.switch_6_i_hallen
      - switch.switch_7_vid_ytterdorren
      - switch.switch_8_vid_tvattstugan
      - switch.switch_9_till_baksidan
      - switch.switch_10_till_gastrummet
      - switch.switch_11_till_kontoret
      - switch.switch_12_vid_altanen
      - switch.switch_3_i_vardagsrummet
  mode: single
- id: '1634837623483'
  alias: Släck på kvällen
  description: ''
  trigger:
  - platform: time
    at: '23:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.switch_1_i_koket
      - switch.switch_4_i_vardagsrummet
      - switch.switch_5_i_vardagsrummet
      - switch.switch_6_i_hallen
      - switch.switch_7_vid_ytterdorren
      - switch.switch_8_vid_tvattstugan
      - switch.switch_9_till_baksidan
      - switch.switch_10_till_gastrummet
      - switch.switch_11_till_kontoret
      - switch.switch_12_vid_altanen
      - switch.switch_3_i_vardagsrummet
  mode: single
- id: '1634837623484'
  alias: Stang av standbygrejer
  description: ''
  trigger:
  - platform: time
    at: 01:00
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.switch_3_i_vardagsrummet
  mode: single
- id: '1642883473750'
  alias: Toggla belysning med shellyknapp
  description: ''
  trigger:
  - platform: mqtt
    topic: shellies/shellybutton1-C45BBE6A5BF3/input_event/0
  condition: []
  action:
  - service: switch.toggle
    target:
      entity_id:
      - switch.switch_1_i_koket
      - switch.switch_2_i_allrumet
      - switch.switch_4_i_vardagsrummet
      - switch.switch_5_i_vardagsrummet
      - switch.switch_6_i_hallen
      - switch.switch_7_vid_ytterdorren
      - switch.switch_8_vid_tvattstugan
      - switch.switch_9_till_baksidan
      - switch.switch_10_till_gastrummet
      - switch.switch_11_till_kontoret
      - switch.switch_12_vid_altanen
  mode: single
- id: '1661340042356'
  alias: Smartladdning
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: f7671d8ade8f586f6fe9efdcf0aaa1dd
    entity_id: sensor.stefans_ipad_battery_level
    domain: sensor
    above: 51
  condition:
  - condition: state
    entity_id: switch.switch_13_laddare_i_k
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.switch_13_laddare_i_k
  mode: restart
- id: '1661341433509'
  alias: Smartladdning, stoppa iPad eller Gottepåsen
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: f7671d8ade8f586f6fe9efdcf0aaa1dd
    entity_id: sensor.stefans_ipad_battery_level
    domain: sensor
    above: 69
  - type: battery_level
    platform: device
    device_id: 60980865acb7a9a3fda5985fa788f6d6
    entity_id: sensor.gottepasen_battery_level
    domain: sensor
    above: 80
    enabled: true
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.switch_13_laddare_i_k
  mode: restart
- id: '1661343087511'
  alias: Smartladdning, iPad start
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: f7671d8ade8f586f6fe9efdcf0aaa1dd
    entity_id: sensor.stefans_ipad_battery_level
    domain: sensor
    below: 10
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.switch_13_laddare_i_k
  mode: restart
- id: '1661348298110'
  alias: Smartladdning, Tesla start
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: ab44d6e858e0f4611d143dd9312ef62d
    entity_id: sensor.electricity_price_planasvagen_7
    domain: sensor
    below: 0.4
  condition: []
  action:
  - type: turn_on
    device_id: 2a23594e3f5c3ece187fec45b7faa2bb
    entity_id: switch.ehvkbqzz_is_enabled
    domain: switch
  mode: restart
- id: '1661371528321'
  alias: Smartladdning, Tesla stop
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: ab44d6e858e0f4611d143dd9312ef62d
    entity_id: sensor.electricity_price_planasvagen_7
    domain: sensor
    above: 0.5
  condition: []
  action:
  - type: turn_off
    device_id: 2a23594e3f5c3ece187fec45b7faa2bb
    entity_id: switch.ehvkbqzz_is_enabled
    domain: switch
  mode: restart
