- id: '1634837623480'
  alias: Tänd på morgonen
  description: ''
  trigger:
  - platform: time
    at: 07:30
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - service: switch.turn_on
    target:
      entity_id:
      - switch.switch_1_i_koket
      - switch.switch_2_i_allrumet
      - switch.switch_4_i_vardagsrummet
      - switch.switch_5_i_vardagsrummet
      - switch.switch_6_i_hallen
      - switch.switch_7_vid_ytterdorren
      - switch.switch_8_vid_tvattstugan
      - switch.switch_9_till_baksidan
      - switch.switch_10_till_gastrummet
      - switch.switch_11_till_kontoret
      - switch.switch_12_vid_altanen
      - switch.switch_3_i_vardagsrummet
  mode: single
- id: '1634837623481'
  alias: Slack när solen går upp
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.switch_1_i_koket
      - switch.switch_2_i_allrumet
      - switch.switch_4_i_vardagsrummet
      - switch.switch_5_i_vardagsrummet
      - switch.switch_6_i_hallen
      - switch.switch_7_vid_ytterdorren
      - switch.switch_8_vid_tvattstugan
      - switch.switch_9_till_baksidan
      - switch.switch_10_till_gastrummet
      - switch.switch_11_till_kontoret
      - switch.switch_12_vid_altanen
      - switch.switch_3_i_vardagsrummet
  mode: single
- id: '1634837623482'
  alias: Tänd när solen går ner
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: time
    before: '22:59'
  action:
  - service: switch.turn_on
    target:
      entity_id:
      - switch.switch_1_i_koket
      - switch.switch_2_i_allrumet
      - switch.switch_4_i_vardagsrummet
      - switch.switch_5_i_vardagsrummet
      - switch.switch_6_i_hallen
      - switch.switch_7_vid_ytterdorren
      - switch.switch_8_vid_tvattstugan
      - switch.switch_9_till_baksidan
      - switch.switch_10_till_gastrummet
      - switch.switch_11_till_kontoret
      - switch.switch_12_vid_altanen
      - switch.switch_3_i_vardagsrummet
  mode: single
- id: '1634837623483'
  alias: Släck på kvällen
  description: ''
  trigger:
  - platform: time
    at: '23:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.switch_1_i_koket
      - switch.switch_4_i_vardagsrummet
      - switch.switch_5_i_vardagsrummet
      - switch.switch_6_i_hallen
      - switch.switch_7_vid_ytterdorren
      - switch.switch_8_vid_tvattstugan
      - switch.switch_9_till_baksidan
      - switch.switch_10_till_gastrummet
      - switch.switch_11_till_kontoret
      - switch.switch_12_vid_altanen
      - switch.switch_3_i_vardagsrummet
  mode: single
- id: '1634837623484'
  alias: Stang av standbygrejer
  description: ''
  trigger:
  - platform: time
    at: 01:00
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.switch_3_i_vardagsrummet
  mode: single
- id: '1642883473750'
  alias: Toggla belysning med shellyknapp
  description: ''
  trigger:
  - platform: mqtt
    topic: shellies/shellybutton1-C45BBE6A5BF3/input_event/0
  condition: []
  action:
  - service: switch.toggle
    target:
      entity_id:
      - switch.switch_1_i_koket
      - switch.switch_2_i_allrumet
      - switch.switch_4_i_vardagsrummet
      - switch.switch_5_i_vardagsrummet
      - switch.switch_6_i_hallen
      - switch.switch_7_vid_ytterdorren
      - switch.switch_8_vid_tvattstugan
      - switch.switch_9_till_baksidan
      - switch.switch_10_till_gastrummet
      - switch.switch_11_till_kontoret
      - switch.switch_12_vid_altanen
  mode: single
