
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

binary_sensor:
  - platform: workday
    country: SWE

sensor:
  - platform: tellstick
    #  116: kallvind
    #  226: krypgrund
    #  240: utomhu

# Tellstick base component
tellstick:
  signal_repetitions: 2

switch:
  - platform: tellstick

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
