
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

recorder:
  purge_keep_days: 180
  commit_interval: 30
   
binary_sensor:
  - platform: workday
    country: SWE

sensor:
  - platform: tellstick
    #  116: kallvind
    #  226: krypgrund
    #  240: utomhu
  - platform: mqtt
    name: Knappen
    state_topic: shellies/shellybutton1-C45BBE6A5BF3/sensor/battery
    unit_of_measurement: "%"
    payload_available: online
    payload_not_available: offline

# Tellstick base component
tellstick:
  signal_repetitions: 2

switch:
  - platform: tellstick

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
