
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

recorder:
  purge_keep_days: 180
  commit_interval: 30

binary_sensor:
  - platform: workday
    country: SE

sensor:
  - platform: tellstick
    only_named:
      - id: 190
        name: Torpargrund
      - id: 240
        name: Utomhus
      - id: 113
        name: Inomhus
  # - platform: mqtt
  #   name: Knappen
  #   state_topic: shellies/shellybutton1-C45BBE6A5BF3/sensor/battery
  #   unit_of_measurement: "%"
  #   payload_available: online
  #   payload_not_available: offline

  # - platform: rest
  #   name: Tibber elpris
  #   resource: https://api.tibber.com/v1-beta/gql
  #   method: POST
  #   payload: '{ "query": "{viewer {homes {currentSubscription {priceInfo {today {total startsAt } tomorrow {total startsAt} }}}}}" }'
  #   json_attributes_path: "$.data.viewer.homes[0].currentSubscription.priceInfo"
  #   json_attributes:
  #     - today
  #     - tomorrow
  #   scan_interval: 86400
  #   value_template: Ok
  #   headers:
  #     Authorization: !secret tibber_token
  #     Content-Type: application/json
  #     User-Agent: REST

  # - platform: template
  #   sensors:
  #     tibber_elpris:
  #       friendly_name: "Timpris"
  #       value_template: >
  #         {% set pris_today = state_attr('sensor.tibber_elpris', 'today') %}
  #         {% for item in pris_today %}
  #           {{ item.total }}
  #         {% endfor %}
  #     elpris_datum:
  #       friendly_name: "Timpris datum"
  #       value_template: >
  #         {% set pris_today = state_attr('sensor.tibber_elpris', 'today') %}
  #         {% for item in pris_today %}
  #           {{ item.startsAt }}
  #         {% endfor %}

# Publish data to influxdb server
shell_command:
  list_sensors: >
    rm -Rf /config/tmp/homeassistant_db_to_influx &&
    mkdir -p /config/tmp/homeassistant_db_to_influx &&
    python3 /config/python_scripts/ls_sensors.py /config/home-assistant_v2.db > /config/tmp/homeassistant_db_to_influx/sensors.txt

  run_sqlite_to_influxdb: >
    mkdir -p /config/homeassistant_db_to_influx &&
    python3 /config/tellstickipi/sqlite_to_influxdb.py --to-path /config/homeassistant_db_to_influx --hours $INFLUXDB_HOURS_TO_PUSH /config/home-assistant_v2.db < /config/tmp/tellstickipi/sensors.txt

  run_upload_to_influxdb: >
    python3 /config/tellstickipi/upload_to_influxdb.py --url $INFLUXDB_URL --token $INFLUXDB_TOKEN --org $INFLUXDB_ORG --bucket $INFLUXDB_BUCKET --from-path /config/tmp/homeassistant_db_to_influx


# Tellstick base component
tellstick:
  signal_repetitions: 2

switch:
  - platform: tellstick

# Text to speech
# tts:
#   - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
